### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by sscirrus** [lucadentella/Yun_SketchUploader#1]
Hi Luca,

Thank you for creating this repo. Can you please tell me a little about the current state? Does it work? Are there any known issues or bugs I should be aware of? Does it do what it claims - allow me to upload sketches via this site to my Yun(s)?

Thanks!
SSCirrus

**Comment by lucadentella** [comment]
Hi! At the moment the project is a bit outdated because of the new Yun images added an "official" way to upload sketches using the main webinterface
